version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev --http-port=8080 --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import

  backend:
    build: .
    environment:
      - SECURITY_ENABLED=true
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/master
      - MONGO_USERNAME=sistemajass
      - MONGO_PASSWORD=ZC7O1Ok40SwkfEje
      - MONGO_DATABASE=JASS_DIGITAL
    depends_on:
      - keycloak
    ports:
      - "8086:8086"


